name: ci

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [ 'v0.20.0', 'v0.19.0', 'v0.18.0' ]
    name: deno ${{ matrix.deno }} sample
    steps:
      - uses: actions/checkout@master
      - name: setup deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno run test/_test.ts
